name: ROS2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: osrf/ros:humble-desktop

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Import ROS2 apt key
      run: |
        sudo apt update
        sudo apt install -y curl gnupg lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o ros.key
        sudo apt-key add ros.key

    - name: Install ROS2 Humble dependencies
      run: |
        sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions python3-rosdep python3-vcstool
        sudo rosdep init
        rosdep update

    - name: Install package dependencies
      run: |
        rosdep install --from-paths src --ignore-src --rosdistro humble -y

    - name: Build the package
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test
        colcon test-result --verbose
